theme: jekyll-theme-minimal
title: 王志勇的主页
description: 记录我的思考与笔记
markdown: kramdown
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
